---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main, edge, dev]
    types:
      - completed
  workflow_dispatch:

jobs:
  workflows:
    uses: lazytarget-homeassistant-apps/workflows/.github/workflows/addon-deploy.yaml@v2.2.0
    permissions:
      contents: read
      packages: write
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
